# Generated by Django 5.0.3 on 2024-03-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Adoption', 'Adoption'), ('MeetAndGreet', 'MeetAndGreet'), ('Vaccination', 'Vaccination')], max_length=100, null=True)),
            ],
        ),
    ]
