# Generated by Django 5.0.3 on 2024-03-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
