# Generated by Django 5.0.3 on 2024-03-27 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_rename_services_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pet_Category', models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird')], max_length=100, null=True)),
                ('BookingAppointment', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meetandgreet',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='petpreference',
            name='ageRange',
        ),
        migrations.AddField(
            model_name='meetandgreet',
            name='PetPreference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.petpreference'),
        ),
        migrations.AddField(
            model_name='petpreference',
            name='adoptionFee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petpreference',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petpreference',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='petpreference',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='petpreference',
            name='species',
            field=models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Availability', models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=100, null=True)),
                ('PetPreference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.petpreference')),
            ],
        ),
        migrations.DeleteModel(
            name='AdoptionApplication',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
