# Generated by Django 5.0.3 on 2024-03-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_vaccination_remove_meetandgreet_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetandgreet',
            name='scheduledAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
