# Generated by Django 5.0.3 on 2024-03-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_meetandgreet_scheduledat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fostering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Condition', models.CharField(blank=True, choices=[('Healthy', 'Healthy'), ('Sick', 'Sick')], max_length=100, null=True)),
                ('AccomodationAvailablity', models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=100, null=True)),
            ],
        ),
    ]
