# Generated by Django 5.0.3 on 2024-03-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_fostering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='BookingAppointment',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
