# Generated by Django 5.0.3 on 2024-03-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_vaccination_bookingappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='petpreference',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
