# Generated by Django 5.0.3 on 2024-04-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_alter_petpreference_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vaccination',
            new_name='Vacci',
        ),
    ]
