# Generated by Django 5.0.3 on 2024-04-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_rename_vaccination_vacci'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacci',
            name='Type',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
